--- #YAML:1.0
name:               Object-Trampoline
version:            1.26
abstract:           delay object construction, and optinally
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          0
    Scalar::Util:  0
    strict:        0
    Symbol:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
